baseURL = "https://richline.rocks/"
languageCode = "en-us"
title = "Dakota Richline"

disableKinds=["RSS"]

[markup.goldmark.renderer]
unsafe= true

[blackfriday]
extensions = [
    "DefinitionLists",
]

[menu]
  [[menu.links]]
    name = "Email: drichline@pm.me"
    url = "mailto:drichline@pm.me"
    weight = "1"

  [[menu.links]]
    name = "Personal site"
    url = "/"
    weight = "2"

  [[menu.links]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/derekrichline/"
    weight = "3"

  [[menu.links]]
    name = "Instagram"
    url = "https://www.instagram.com/richline.rocks/"
    weight = "4"

  [[menu.links]]
    name = "Books I've Enjoyed"
    url = "/booklist"
    weight = "5"
